accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),

]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('',views.index,name='index'),
    path('create/',views.create,name='create'),
    path('<int:id>/',views.detail,name='detail'),
    path('<int:id>/delete/',views.delete,name='delete'),
    path('<int:id>/update/',views.update,name='update'),

    path('<int:article_id>/comments/create/',views.comment_create,name='comment_create'),
    path('<int:article_id>/comments/<int:id>/delete/',views.comment_delete,name='comment_delete'),
    
]

auth/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
    path('accounts/',include('accounts.urls')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass
    # aritcle_set = 자동 컬럼추가
    # comment_set 

articles/models.py
from django.db import models
from accounts.models import User # 방법1
from django.conf import settings # 방법2
from django.contrib.auth import get_user_model # 방법3

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    #유저모델을 참조하는경우
    # 방법1.(권장X)
    # user = models.ForeignKey(User,on_delete=models.CASCADE)

    #방법2.(권장0) settings.AUTH_USER_MODEL == 'accounts.User'

    # user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    #방법3. (권장0)
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    
    # 1:N 에서 1은 _id, N은 _set
    #comment_set = 장고가 자동으로 추가해주는 컬럼
    #user_id

class Comment(models.Model):
    content =  models.TextField()
    article = models.ForeignKey(Article,on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)

    #article_id = 장고가 자동으로 컬럼 추가
    #user_id 
    

accounts/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields


class CustomAuthenticationForm(AuthenticationForm):
    pass

articles/forms.py
from django import forms
from .models import Article,Comment

class ArticleForm(forms.ModelForm):
    # title = forms.CharField(
    #     label='제목입니다',
    #     widget=forms.TextInput(
    #         attrs={'class':'form-control'}
    #     )
    # )

    # content = forms.CharField(
    #     label='내용',
    #     widget=forms.Textarea(
    #         attrs={'class':'form-control'}
    #     )
    # )

    class Meta:
        model = Article
        # fields = '__all__'
        exclude = ('user',)


class CommentForm(forms.ModelForm):
    class Meta:         
        model = Comment
        fields = ('content',)
    

accounts/views.py
from django.shortcuts import render,redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid(): #올바른 입력한 경우: 흔한비밀번호 X
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }

    return render(request, 'signup.html',context)


def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid(): 
            #로그인
            auth_login(request,form.get_user())

            # http://127.0.0.1:8000/accounts/login/  #?는 GET요청
            # next_url = request.GET.get('next') => NONE반환 키값이 없기때문에
            # return redirect('articles:index')
        
            #http://127.0.0.1:8000/accounts/login/?next=/articles/create/ => '/articles/create'
            next_url = request.GET.get('next')
            return redirect(next_url or 'articles:index')
            # by 단축평가
            # next 인자에 url이 있을때 => '/articles/create/' or 'articles:index' => '/articles/create/'
            # next 인자에 url 있을때 => None or 'articles:index' => 'articles:index'
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }

    return render(request, 'login.html',context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

articles/views.py
from django.shortcuts import render,redirect
from .forms import ArticleForm,CommentForm
from .models import Article, Comment
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles
    }

    return render(request,'index.html',context)


@login_required #@ create전에 이거 먼저 실행해야 되게 만듬
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()

    context = {
        'form': form
    }    
    
    return render(request,'form.html', context)


def detail(request,id):
    article = Article.objects.get(id=id)
    form = CommentForm()

    context={
        'article':article,
        'form': form
    }

    return render(request,'detail.html',context)


@login_required
def delete(request,id):
    article = Article.objects.get(id=id)

    if request.user == article.user:
        article.delete()

    return redirect('articles:index')


@login_required
def update(request, id):
    article = Article.objects.get(id=id)

    if request.user != article.user:
        return redirect('articles:detail',id=id)
    
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article) #기존정보 + 새로운정보 덮어씌우기
        if form.is_valid():
            form.save()
            return redirect('articles:detail', id=id)
    else:
        form = ArticleForm(instance=article) # 기존 정보

    context = {
        'form': form
    }

    return render(request,'form.html',context)


@login_required
def comment_create(request, article_id):
    form = CommentForm(request.POST)
    # article = Article.objects.get(id=id)

    if form.is_valid():
        comment =form.save(commit=False)
        # comment.user = request.user
        # comment.article = article

        comment.user_id = request.user.id
        comment.article_id= article_id

        comment.save()

        return redirect('articles:detail',id=article_id)

@login_required
def comment_delete(request, article_id, id):
    comment = Comment.objects.get(id=id)

    if request.user == comment.user:
        comment.delete()    

    return redirect('articles:detail',id=article_id)

accounts/templates/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}


{% block body%}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
{% endblock%}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}


{% block body%}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary">
    </form>
{% endblock%}

articles/templates/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}


{% block body %}
    <div class="card">
        <div class="card-header">{{article.user}}</div>
        <div class="card-body">
            <h5 class="card-title">{{article.title}}</h5>
            <p class="card-text">{{article.content}}</p>
        </div>
    </div>

    {% if user == article.user %}
        <a href="{% url 'articles:delete' id=article.id %}">delete</a>
        <a href="{% url  'articles:update' id=article.id %}">update</a>
    {% endif %}
    <hr>

    {% if user.is_authenticated %}
        <form action="{% url 'articles:comment_create' article_id=article.id %}" method='POST'>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary">
        </form>
        <hr>
    {% endif %}

    {% for comment in article.comment_set.all %}
        <div class="alert alert-primary">
            {{comment.user}}:{{comment.content}}
            {% if user == comment.user %}
            <a class="btn btn-danger btn-sm" href="{% url 'articles:comment_delete' article_id=article.id id=comment.id%}">delete</a>
            {% endif %}
        </div>
            

    {% endfor %}
{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body%}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
{% endblock%}

articles/templates/index.html
{% extends 'base.html' %}

{% block body%}
    <h1>index</h1>
    {% for article in articles %}
        <h3>{{article.title}}</h3>
        <h3>{{article.user}}</h3>
        <a href="{% url 'articles:detail' id=article.id%}">detail</a>
        <hr>
    {% endfor %}

{% endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'articles:index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'articles:create' %}">Create</a>
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        <a class="nav-link disabled" aria-disabled="true">{{user}}</a>
                    {% else %}
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">Signup</a>
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block body%}
        {% endblock%}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>